"""add cognito_sub to users

Revision ID: 2ffa1a7bab47
Revises: fa93ab25cb51
Create Date: 2026-08-21 12:03:13.743050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffa1a7bab47'
down_revision: Union[str, Sequence[str], None] = 'fa93ab25cb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cognito_sub', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['cognito_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'cognito_sub')
    # ### end Alembic commands ###
