"""add workout templates and set distance fields

Revision ID: 818a5304d16a
Revises: a5df2e4189de
Create Date: 2026-08-22 12:55:18.225723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '818a5304d16a'
down_revision: Union[str, Sequence[str], None] = 'a5df2e4189de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_template_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('workout_sets', sa.Column('distance', sa.Numeric(), nullable=True))
    op.add_column('workout_sets', sa.Column('distance_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_sets', 'distance_unit')
    op.drop_column('workout_sets', 'distance')
    op.drop_table('workout_template_exercises')
    op.drop_table('workout_templates')
    # ### end Alembic commands ###
