"""add exercise category, movement_pattern, logging_type

Revision ID: a5df2e4189de
Revises: 2ffa1a7bab47
Create Date: 2026-08-21 21:56:27.470515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5df2e4189de'
down_revision: Union[str, Sequence[str], None] = '2ffa1a7bab47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('category', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('movement_pattern', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('logging_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'logging_type')
    op.drop_column('exercises', 'movement_pattern')
    op.drop_column('exercises', 'category')
    # ### end Alembic commands ###
